/**
 * @file app shell mutation types
 * @author paulwang007(12900985@qq.com)
 */

export const ENABLE_PAGE_TRANSITION = 'ENABLE_PAGE_TRANSITION';
export const DISABLE_PAGE_TRANSITION = 'DISABLE_PAGE_TRANSITION';
export const SET_PAGE_SWITCHING = 'SET_PAGE_SWITCHING';
export const SET_PAGE_TRANSITION_NAME = 'SET_PAGE_TRANSITION_NAME';
export const SET_APP_HEADER = 'SET_APP_HEADER';
export const SET_APP_BOTTOM_NAV = 'SET_APP_BOTTOM_NAV';
export const ACTIVATE_APP_BOTTOM_NAV = 'ACTIVATE_APP_BOTTOM_NAV';
export const SET_SIDEBAR_VISIBILITY = 'SET_SIDEBAR_VISIBILITY';
export const SAVE_SCROLLTOP = 'SAVE_SCROLLTOP';
export const SET_APPLICATIONS = 'SET_APPLICATIONS';
export const CHANGE_APP ='CHANGE_APP';

export const SET_USER ='SET_USER';
export const SET_TOKEN ='SET_TOKEN';
export const SET_BLOCKS ='SET_BLOCKS';
export const SET_AUTHENTICATED ='SET_AUTHENTICATED';
export const SET_APP_MENUS = 'SET_APP_MENUS';

